Create CommandReply Broker
Clariteia/minos_microservice_networks pull request #137
Opened 2021-05-18 10:40 UTC by vladyslav-fenchak

CommandReply Broker #123

2021-05-18 12:59 UTC, garciparedes requested changes
Hi @vladyslav-fenchak! I think that by mistake you ha've included docs-related files. Could you remove?

2021-05-18 13:02 UTC, garciparedes commented
To avoid these kinds of problems, I'll create a issue to update the `.gitignore` and exclude these files to avoid future cases like this one. 😊

2021-05-18 15:17 UTC, garciparedes approved these changes
Hi again @vladyslav-fenchak, I've already seen that you've already fixed the troubles related with the documentation. 

After checking the changes I need to say that it looks good to me!

2021-05-18 16:23 UTC, andrea-mucci approved these changes

2021-05-19 08:22 UTC, andrea-mucci approved these changes

2021-05-19 08:22 UTC, merged